### ISSUE TITLE
How to properly dispose of Room Activity

### ISSUE THREAD

**Issue by xhozst** [xamarin-bindings-for-twilio/TwilioVideoXamarinAndroid#4]
This binding is great and I have it working with a remote participant, video, and audio. However, I have issues when trying to close the RoomActivity. What's the recommended way to tear down a room and properly dispose of resources?

I have tried the following;

			if (room != null)
			{
				room.Disconnect();
				room.Dispose();
				room = null;
			}
			if (participantListener != null)
			{
				participantListener.Dispose();
				participantListener = null;
			}
			if (roomListener != null)
			{
				roomListener.Dispose();
				roomListener = null;
			}
			if (localAudioTrack != null)
			{
				//localAudioTrack.Release();
				localAudioTrack.Dispose();
				localAudioTrack = null;
			}
			if (localVideoTrack != null)
			{
				//localVideoTrack.Release();
				//localVideoTrack.RemoveSink(myCamView);
				localVideoTrack.Dispose();
				localVideoTrack = null;
			}

However I get an exception if connected when closing;

    System.NotSupportedException "Unable to activate instance of type ProjectName.RoomListenerClass from native handle"

Otherwise if not connected (connect failure etc). I can still see a lot of messages in the background as if things are still running;

    [tvi.webrtc.Logging] EglRenderer: CamMyCamDropping frame - Not initialized or already released.

**Comment by jtorvald** [comment]
I have this, but please let me know if I'm missing something:

```
        protected override void OnDestroy()
        {
            /*
             * Always disconnect from the room before leaving the Activity to
             * ensure any memory allocated to the Room resource is freed.
             */
            if (room != null && room.GetState() != Room.State.Disconnected)
            {
                room.Disconnect();
            }

            if (screenVideoTrack != null)
            {
                screenVideoTrack.Release();
                screenVideoTrack = null;
            }

            /*
             * Release the local audio and video tracks ensuring any memory allocated to audio
             * or video is freed.
             */
            if (localAudioTrack != null)
            {
                localAudioTrack.Release();
                localAudioTrack = null;
            }
            if (localVideoTrack != null)
            {
                localVideoTrack.Release();
                localVideoTrack = null;
            }

            base.OnDestroy();
        }
```

**Comment by jtorvald** [comment]
Didn't hear anything so I'm closing this issue
